server:
  port: 8080
spring:
  liquibase:
    change-log: classpath:/db/changelog/changelog.yml
  datasource:
#    url: jdbc:postgresql://pix-db/pix-db
    url: jdbc:postgresql://localhost:5432/pix-db
    username: pix-admin
    password: admin@1234
    driver-class-name: org.postgresql.Driver
