version: '3.8'

services:
  pix-db:
    hostname: pix-db
    image: postgres
    restart: always
    volumes:
      - /pix-db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin@1234
      POSTGRES_USER: pix-admin
      POSTGRES_DB: pix-db
    ports:
      - "5432:5432"
    network_mode: host

  pix-producer-api:
    build: .
    image: pix-producer-api
    depends_on:
      - pix-db
      - zookeeper
      - kafka
    network_mode: host

volumes:
  pix-db:
